#!/bin/bash

# MIT License
# -----------
# 
# Copyright (c) 2018-2021 Shift Clan (http://shift-ac.com)
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

if [ $# = 0 ]; then
    echo "ShiftAC's mkjproj 1.2: initialize a java project."
    echo "Usage: $0 [name]"
    exit
fi

pos=$(dirname $(readlink "$0" -f))
res="$pos/../resource/mkjproj"

mkdir "$1"
mkdir "$1/src"
mkdir "$1/bin"
mkdir "$1/temp"
mkdir "$1/test"
mkdir "$1/lib"

echo "# $1" > "$1/README.md"
cat "$res/makefile.src.template" | sed "s/\$1/$1/g" > "$1/src/Makefile"
cat "$res/makefile.template" | sed "s/\$1/$1/g" > "$1/Makefile"
cat "$res/gitignore.template" | sed "s/\$1/$1/g" > "$1/.gitignore"
cp "$res/generateLib" "$1/lib/"
chmod +x "$1/lib/generateLib"
cp "$res/gitattribute.template" "$1/.gitattribute"

git init "$1" --quiet
